### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ComputerGooroo** [chasem-dev/LeagueofCrafters#17]
---- Minecraft Crash Report ----
// You're mean.

Time: 1/3/14 6:51 AM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 1
    at cpw.mods.fml.client.registry.KeyBindingRegistry$KeyHandler.keyTick(KeyBindingRegistry.java:121)
    at cpw.mods.fml.client.registry.KeyBindingRegistry$KeyHandler.tickStart(KeyBindingRegistry.java:102)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:361)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1511)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 83858696 bytes (79 MB) / 189423616 bytes (180 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 4 mods loaded, 4 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    LoC{0.2.2} [League Of Crafters](LeagueofCraftersV0.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.6.4-Forge9.11.1.953
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 7800 Series GL version 4.3.12618 Compatibility Profile Context 13.251.0.0, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by chasem-dev** [comment]
Does this happen when you press te 'f' key by chancce?

**Comment by ComputerGooroo** [comment]
no it was when I held shift+v to do V4.0 in my world name
